In [1]:
import pandas as pd
df = pd.read_csv("global_fuel_prices_2020_2026.csv")

Corrélation avec le Brent : voir si les prix à la pompe suivent les cours du pétrole brut.

In [3]:
df[["petrol_usd_liter","diesel_usd_liter","lpg_usd_liter","brent_crude_usd"]]

       petrol_usd_liter  diesel_usd_liter  lpg_usd_liter  brent_crude_usd
0                 1.465             1.289          1.093            65.75
1                 1.435             1.319          1.077            65.54
2                 1.446             1.329          1.080            66.51
3                 1.488             1.359          1.125            68.79
4                 1.457             1.341          1.111            68.44
...                 ...               ...            ...              ...
27463             3.036             2.849          2.294           130.00
27464             3.020             2.861          2.248           130.00
27465             3.072             2.825          2.334           130.00
27466             3.045             2.816          2.282           130.00
27467             3.064             2.846          2.296           130.00

[27468 rows x 4 columns]

corelation essense-petrol

In [7]:
df[["petrol_usd_liter","brent_crude_usd"]].corr()

                  petrol_usd_liter  brent_crude_usd
petrol_usd_liter           1.00000          0.26353
brent_crude_usd            0.26353          1.00000

corelation diesel-petrol

In [8]:
df[["diesel_usd_liter","brent_crude_usd"]].corr()

                  diesel_usd_liter  brent_crude_usd
diesel_usd_liter          1.000000         0.258848
brent_crude_usd           0.258848         1.000000

corelation gaz-petrol

In [9]:
df[["lpg_usd_liter","brent_crude_usd"]].corr()

                 lpg_usd_liter  brent_crude_usd
lpg_usd_liter          1.00000          0.26349
brent_crude_usd        0.26349          1.00000

Impact des subventions : comparer les pays avec subventions vs sans subventions.

In [11]:
df["subsidy_level"].value_counts()

subsidy_level
Low          14388
Medium        5886
High          3924
Very High     3270
Name: count, dtype: int64

In [12]:
df.groupby("subsidy_level")["petrol_usd_liter"].mean()

subsidy_level
High         0.709049
Low          3.450598
Medium       1.659342
Very High    0.147783
Name: petrol_usd_liter, dtype: float64

In [13]:
df.groupby("subsidy_level")["diesel_usd_liter"].mean()

subsidy_level
High         0.650345
Low          3.244463
Medium       1.519537
Very High    0.132368
Name: diesel_usd_liter, dtype: float64

In [14]:
df.groupby("subsidy_level")["lpg_usd_liter"].mean()

subsidy_level
High         0.531346
Low          2.587990
Medium       1.244496
Very High    0.111507
Name: lpg_usd_liter, dtype: float64

Taxes : analyser si les pays avec forte taxation ont systématiquement des prix plus élevés.

In [18]:
df["tax_group"] = pd.cut(
    df["tax_percentage"],
    bins=[0,15,30,100],
    labels = ["Low","Medium","Hight"],
    include_lowest=True)

In [20]:
df.groupby("tax_group")["petrol_usd_liter"].mean()

tax_group
Low       1.411954
Medium    1.929124
Hight     3.446373
Name: petrol_usd_liter, dtype: float64

In [21]:
df.groupby("tax_group")["diesel_usd_liter"].mean()

tax_group
Low       1.307638
Medium    1.797738
Hight     3.240687
Name: diesel_usd_liter, dtype: float64

In [22]:
df.groupby("tax_group")["lpg_usd_liter"].mean()

tax_group
Low       1.058997
Medium    1.446860
Hight     2.584842
Name: lpg_usd_liter, dtype: float64