In [1]:
import pandas as pd
df = pd.read_csv("global_fuel_prices_2020_2026.csv")

Prix moyen par carburant (essence, diesel, GPL) sur toute la période.

In [2]:
df[["date","petrol_usd_liter","diesel_usd_liter","lpg_usd_liter"]]

             date  petrol_usd_liter  diesel_usd_liter  lpg_usd_liter
0      2020-01-06             1.465             1.289          1.093
1      2020-01-13             1.435             1.319          1.077
2      2020-01-20             1.446             1.329          1.080
3      2020-01-27             1.488             1.359          1.125
4      2020-02-03             1.457             1.341          1.111
...           ...               ...               ...            ...
27463  2026-03-09             3.036             2.849          2.294
27464  2026-03-16             3.020             2.861          2.248
27465  2026-03-23             3.072             2.825          2.334
27466  2026-03-30             3.045             2.816          2.282
27467  2026-04-06             3.064             2.846          2.296

[27468 rows x 4 columns]

In [3]:
print(df["petrol_usd_liter"].mean())

2.281915246832678

In [4]:
print(df["diesel_usd_liter"].mean())

2.1337601936799184

In [5]:
print(df["lpg_usd_liter"].mean())

1.7114726226882189

Comparer les régions : prix moyen par région et par carburant.

In [6]:
df["region"].value_counts()

region
Europe           7521
Africa           7521
Asia             5559
Middle East      2943
South America    2289
North America     981
Oceania           654
Name: count, dtype: int64

In [7]:
df.groupby("region")["petrol_usd_liter"].mean()

region
Africa           1.549482
Asia             2.140571
Europe           3.701695
Middle East      1.225935
North America    2.064176
Oceania          3.655203
South America    1.425393
Name: petrol_usd_liter, dtype: float64

In [8]:
df.groupby("region")["diesel_usd_liter"].mean()

region
Africa           1.426697
Asia             1.976584
Europe           3.517597
Middle East      1.141471
North America    1.892420
Oceania          3.466560
South America    1.290224
Name: diesel_usd_liter, dtype: float64

In [9]:
df.groupby("region")["lpg_usd_liter"].mean()

region
Africa           1.162121
Asia             1.605441
Europe           2.776193
Middle East      0.919475
North America    1.548336
Oceania          2.742182
South America    1.069333
Name: lpg_usd_liter, dtype: float64

Top 5 pays les plus chers pour l’essence en 2025.

In [10]:
df["date"] = pd.to_datetime(df["date"])

In [11]:
df_2025 = df[df["date"].dt.year ==2025]
df_2025[["date","country","petrol_usd_liter"]]

            date        country  petrol_usd_liter
261   2025-01-06  United States             2.710
262   2025-01-13  United States             2.672
263   2025-01-20  United States             2.670
264   2025-01-27  United States             2.631
265   2025-02-03  United States             2.583
...          ...            ...               ...
27449 2025-12-01         Rwanda             2.709
27450 2025-12-08         Rwanda             2.804
27451 2025-12-15         Rwanda             2.788
27452 2025-12-22         Rwanda             2.746
27453 2025-12-29         Rwanda             2.728

[4368 rows x 3 columns]

In [12]:
df_2025.groupby("country")["petrol_usd_liter"].mean().sort_values().head(5)

country
Venezuela    0.014750
Iran         0.041731
Libya        0.062885
Algeria      0.156423
Egypt        0.190000
Name: petrol_usd_liter, dtype: float64

In [13]:
df_2025.groupby("country")["petrol_usd_liter"].mean().sort_values(ascending=False).head(5)

country
Hong Kong      6.167269
Norway         5.299154
Netherlands    5.180904
Ireland        5.178885
Singapore      5.055673
Name: petrol_usd_liter, dtype: float64