In [1]:
import pandas as pd
df = pd.read_csv("global_fuel_prices_2020_2026.csv")

Volatilité

In [2]:
df.groupby("country")["petrol_usd_liter"].std().sort_values()

country
Venezuela      0.009276
Iran           0.019769
Libya          0.021874
Algeria        0.032652
Egypt          0.035536
                 ...
Singapore      0.809914
Ireland        0.829552
Netherlands    0.830929
Norway         0.847940
Hong Kong      0.987426
Name: petrol_usd_liter, Length: 84, dtype: float64

In [3]:
df.groupby("country")["diesel_usd_liter"].std().sort_values()

country
Venezuela      0.011586
Iran           0.018839
Libya          0.021016
Algeria        0.028975
Iraq           0.031235
                 ...
Denmark        0.770069
Netherlands    0.771249
Norway         0.790025
Ireland        0.808104
Hong Kong      0.907057
Name: diesel_usd_liter, Length: 84, dtype: float64

In [4]:
df.groupby("country")["lpg_usd_liter"].std().sort_values()

country
Venezuela      0.009880
Iran           0.018335
Libya          0.021791
Algeria        0.028992
Egypt          0.030672
                 ...
Singapore      0.608711
Ireland        0.622509
Netherlands    0.624407
Norway         0.638108
Hong Kong      0.740203
Name: lpg_usd_liter, Length: 84, dtype: float64

Classement dynamique : chaque année, identifier le pays le plus cher et le moins cher en essence.

In [5]:
df["date"] = pd.to_datetime(df["date"])

In [6]:
df["year"]= df["date"].dt.year

In [7]:
df.groupby(["year","country"])["petrol_usd_liter"].mean().reset_index().loc[
    lambda x: x.groupby("year")["petrol_usd_liter"].idxmax()]

     year    country  petrol_usd_liter
24   2020  Hong Kong          3.605462
108  2021  Hong Kong          5.537058
192  2022  Hong Kong          6.082346
276  2023  Hong Kong          5.420481
360  2024  Hong Kong          6.180245
444  2025  Hong Kong          6.167269
528  2026  Hong Kong          6.426643

In [8]:
df.groupby(["year","country"])["petrol_usd_liter"].mean().reset_index().loc[
    lambda x: x.groupby("year")["petrol_usd_liter"].idxmin()]

     year    country  petrol_usd_liter
80   2020  Venezuela          0.013462
164  2021  Venezuela          0.015750
248  2022  Venezuela          0.016923
332  2023  Venezuela          0.015423
416  2024  Venezuela          0.016906
500  2025  Venezuela          0.014750
584  2026  Venezuela          0.016571

Groupby multi-index : prix moyen par (année, région, carburant).

In [9]:
df.groupby("year")["petrol_usd_liter"].mean()

year
2020    1.484851
2021    2.279826
2022    2.505177
2023    2.233670
2024    2.545121
2025    2.539506
2026    2.646955
Name: petrol_usd_liter, dtype: float64

In [10]:
df.groupby("region")["petrol_usd_liter"].mean()

region
Africa           1.549482
Asia             2.140571
Europe           3.701695
Middle East      1.225935
North America    2.064176
Oceania          3.655203
South America    1.425393
Name: petrol_usd_liter, dtype: float64

In [11]:
df["petrol_usd_liter"].mean()

np.float64(2.281915246832678)

In [12]:
df["diesel_usd_liter"].mean()

np.float64(2.1337601936799184)

In [13]:
df["lpg_usd_liter"].mean()

np.float64(1.7114726226882189)

Resampling : transformer les données hebdomadaires en moyennes mensuelles pour lisser les tendances.

In [14]:
df["year"].value_counts()

year
2024    4452
2020    4368
2021    4368
2022    4368
2023    4368
2025    4368
2026    1176
Name: count, dtype: int64

In [15]:
df["date"] = pd.to_datetime(df["date"])

In [16]:
df = 
df_monthly = df[["petrol_usd_liter","diesel_usd_liter","lpg_usd_liter"]].resample("ME").mean()

TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'RangeIndex'

In [ ]:
print(df_monthly)